language: python

python:
  - "3.6"

# command to install dependencies
install: 
  - pip3 install -q -r requirements.txt
  - pip3 install -q -r source/_scripts/_python/requirements.txt

# command to run tests
script: 
  - make py
  - make htmlall
  #- make linkcheck

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  repo: intelkevinputnam/rtd-build-target
  target-branch: master
  on:
    branch: rtd-theme
  local_dir: source/_build/html/

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: source/_build/html/**/*
  on:
    tags: true