language: python

python:
  - "3.6"

# command to install dependencies
install: 
  - pip3 install -q -r requirements.txt
  - pip3 install -q -r source/_scripts/_python/requirements.txt

# command to run tests
script: 
  - make py
  - make htmlall
  #- make linkcheck

before_deploy:
  - tar -zcvf clearlinux-docs.tar.gz -C source/_build/html/ .

deploy:
 - provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN
   keep-history: true
   repo: intelkevinputnam/rtd-build-target
   target-branch: master
   on:
     branch: rtd-theme
   local_dir: source/_build/html/
 - provider: releases
   skip_cleanup: true
   api_key: $GITHUB_TOKEN
   file: clearlinux-docs.tar.gz
   on:
     tags: true
 - provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN
   keep-history: true
   repo: intelkevinputnam/rtd-build-target
   target-branch: $TRAVIS_TAG
   on:
     tags: true
   local_dir: source/_build/html/ 