language: python

python:
  - "3.6"

# command to install dependencies
install: 
  - pip3 install -q -r requirements.txt
  - pip3 install -q -r source/_scripts/_python/requirements.txt

# command to run tests
script: 
  - make py
  - make htmlall
  - wget https://github.com/intelkevinputnam/rtd-build-source/releases/latest/download/clearlinux-docs.tar.gz
  - tar xf clearlinux-docs-zh-CN.tar.gz -C source/_build/html/zh_CN

before_deploy:
  - tar -zcvf clearlinux-docs-zh-CN.tar.gz -C source/_build/html_zh_CN .

deploy:
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file: clearlinux-docs-zh-CN.tar.gz
    on:
      tags: true
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    target-branch: latestHTML
    on:
      branch: master
    local_dir: source/_build/html/

